import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_component/header/Header";
import { AuthProvider } from "../context/AuthContext";
const fs = require("fs");
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(
    "process.env.GOOGLE_APPLICATION_CREDENTIALS",
    process.env.GOOGLE_APPLICATION_CREDENTIALS
  );
  const a = fs.readFileSync(process.env.GOOGLE_APPLICATION_CREDENTIALS, "utf8");
  console.log("asdasdasdas", a);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
