import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_component/header/Header";
import { AuthProvider } from "../context/AuthContext";
import RQProvider from "./_component/RQProvider";
const fs = require("fs");
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </RQProvider>
      </body>
    </html>
  );
}
